# This is a basic workflow to help you get started with Actions

name: pipeline for python microservice

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: docker-greetings
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      
  deploy-to-dev:
    runs-on: docker-greetings
    needs: build-docker-image
    steps:
      - uses: ./github/actions/deploy
        with:
          environment: dev

  
  tests-on-dev:
    runs-on: docker-greetings
    needs: deploy-to-dev
    steps:
      - name: tests-on-dev
        run: |
          echo "Running integration tests on DEV..."
          docker pull martinowl/api-tests:latest
          docker run --network=host --rm martinowl/api-tests:latest run greetings greetings_dev


  deploy-to-stg:
    runs-on: docker-greetings
    needs: tests-on-dev
    steps:
      - uses: ./github/actions/deploy
        with:
          environment: stg

  tests-on-stg:
    runs-on: docker-greetings
    needs: deploy-to-stg
    steps:
      - name: tests-on-dev
        run: |
          echo "Running integration tests on STG..."
          docker pull martinowl/api-tests:latest
          docker run --network=host --rm martinowl/api-tests:latest run greetings greetings_stg

  deploy-to-prod:
    runs-on: docker-greetings
    needs: tests-on-stg
    steps:
      - uses: ./github/actions/deploy
        with:
          environment: dev

  tests-on-prod:
    runs-on: docker-greetings
    needs: deploy-to-prod
    steps:
      - name: tests-on-dev
        run: |
          echo "Running integration tests on PROD..."
          docker pull martinowl/api-tests:latest
          docker run --network=host --rm martinowl/api-tests:latest run greetings greetings_prod

  