# This is a basic workflow to help you get started with Actions

name: pipeline for python microservice

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: docker-greetings
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      
  deploy-to-dev:
    runs-on: docker-greetings
    needs: build-docker-image
    steps:
      - uses: ./.github/actions/deploy
        with:
          deploy-to: dev

  
  tests-on-dev:
    runs-on: docker-greetings
    needs: deploy-to-dev
    steps:
      - uses: ./.github/actions/test
        with:
          test-env: dev      


  deploy-to-stg:
    runs-on: docker-greetings
    needs: tests-on-dev
    steps:
      - uses: ./.github/actions/deploy
        with:
          deploy-to: stg

  tests-on-stg:
    runs-on: docker-greetings
    needs: deploy-to-stg
    steps:
      - uses: ./.github/actions/test
        with:
          test-env: stg 

  deploy-to-prod:
    runs-on: docker-greetings
    needs: tests-on-stg
    steps:
      - uses: ./.github/actions/deploy
        with:
          deploy-to: prod

  tests-on-prod:
    runs-on: docker-greetings
    needs: deploy-to-prod
    steps:
      - uses: ./.github/actions/test
        with:
          test-env: prod

  