# This is a basic workflow to help you get started with Actions

name: pipeline for python microservice

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: docker-greetings
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t martinowl/python-greetings:latest . 
      
      - name: Push image
        run: docker push martinowl/python-greetings:latest
      
  deploy-to-dev:
    runs-on: docker-greetings
    steps:
      - name: deploy to dev
        run: |
          echo "Deploying Python microservice to DEV environment"
          docker pull martinowl/python-greetings-app:latest
          docker-compose stop greetings-app-dev
          docker compose rm -f greetings-app-dev
          docker compose up -d greetings-app-dev

  
  # tests-on-dev:
  #   runs-on: docker-greetings

  # deploy-to-stg:
  #   runs-on: docker-greetings

  # tests-on-stg:
  #   runs-on: docker-greetings

  # deploy-to-prod:
  #   runs-on: docker-greetings

  # tests-on-prod:
  #   runs-on: docker-greetings

  